### ISSUE TITLE
A guide on how to write tests easily

### ISSUE THREAD

**Issue by SnowballSH** [Tech-With-Tim/Frontend#8]
**Is your feature request related to a problem? Please describe.**
Please (M7MD) add a guide regarding how to write tests easily. Sometimes I finish a feature and I don't know how to write tests for it :stonks:

**Describe the solution you'd like**
A markdown file guiding step-by-step how to write a test for frontend.

**Describe alternatives you've considered**
1. Remove tests completely (probably not)
2. Idk

**Additional context**
No need to be really detailed just give a template or guide so we know how to write a tests for it.

Thanks,
SandsquareSH

(actually part of the reason for this issue is to test the function uganda)

**Comment by mohamed040406** [comment]
Just Copy as if you don't know how to (and i already told you to copy tests i wrote)
